apiVersion: apps/v1
kind: Deployment

metadata:
  name: ros2-jazzy-demo
  namespace: production
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ros2-publisher

  template:
    metadata:
      labels:
        app: ros2-publisher

    spec:
      containers:

      - name: ros2-publisher

        image: prodacr001.azurecr.io/ros2-jazzy-demo:$(Build.BuildId)

        imagePullPolicy: Always
        ports:
        - containerPort: 80

        resources:
        
          requests:
            memory: "128Mi"
            cpu: "100m"
 
          limits:
            memory: "512Mi"
            cpu: "500m"

        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1