apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ros2-ingress
  namespace: production

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - 20-253-93-207.nip.io
      secretName: ros2-tls

  rules:
    - host: 20-253-93-207.nip.io

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: ros2-service
                port:
                  number: 80